version: '3.8'

services:
  app:
    build: ./app

  server:
    build: ./server
    environment:
      RUST_LOG: INFO
      KDLE_PORT: 3000
      KDLE_RATE_NUM: 3
      KDLE_RATE_PER: 6

  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 1080:80
      # - 443:443
      # - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - server
